apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
      - name: setup
        image: rotati/webapp:68b8c08
        command: ["/bin/bash", "./setup.production.sh"]
        # command: ["/bin/bash","-c"]
        # args: ["/home/app/webapp/bin/rake db:create && /home/app/webapp/bin/rake db:migrate"]
        env:
        - name: PASSENGER_APP_ENV
          value: production
      restartPolicy: Never